name: ml4chem

channels:
    - anaconda
    - pytorch

dependencies:
    - python==3.7
    - pytorch
    - pip:
        - matplotlib
        - pyyaml
        - sphinx-gallery
        - sphinxcontrib-napoleon
        - sphinxcontrib-bibtex
        - sphinxcontrib-inlinesyntaxhighlight
        - ase
        - m2r
