name: mlchem

channels:
    - anaconda
    - pytorch
    - conda-forge


dependencies:
    - python==3.7
    - pytorch
    - matplotlib
    - pip:
        - pyyaml
        - sphinx-gallery
        - sphinxcontrib-napoleon
        - sphinxcontrib-bibtex
        - sphinxcontrib-inlinesyntaxhighlight
        - ase
